import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Landing from "@/components/landing";
import ScrollObserver from "@/lib/scroll-observer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wowdoa Synmage",
  description: "Generated by create next app",
  authors: [{ name: "Ranaco", url: "https://github.com/Ranaco" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ScrollObserver>
          <div
            style={{
              height: "100%",
              width: "100%",
            }}
          >
            <Landing />
            <div
              style={{
                height: "100%",
                width: "100%",
                flex: 1,
                zIndex: 2,
              }}
            >
              {children}
            </div>
          </div>
        </ScrollObserver>
      </body>
    </html>
  );
}
